---
- hosts: localhost
  connection: local
  gather_facts: true
  name: "Convert human inputs to bytes for proper volume sizes."
#  This "function" assumes all inputs are in BYTES, if Bits is wanted replace 
#  B with b and use human_to_bytes(isbits=true)
#
#
#

  tasks:
    - name: "Create local vars"                                                                                         #Used for Testing
      ansible.builtin.set_fact:
        sizes:
          - "1"
          - "1 gb"
          - "1 GB"
          - "2 tb"
          - "2 t"
          - "2.3 t"
          - "2,3 t"
          - "2,3 tBytes"
          - "2,3 tByts"
          - "35t"
          - "15t"
        reserve: 10

    - name: Debug                                                                                                       #https://docs.saltproject.io/en/master/topics/jinja/index.html
      ansible.builtin.debug:
        msg:                        "Input: {{ item }}, value in bytes: {{
                                     ( ( item | replace('b','B') | replace(',','.') | human_to_bytes(default_unit='GB') ) / ( 1 - ( reserve / 100 ) ) ) | int 
                                    }}"
      loop: "{{ sizes }}"
