---
- hosts: localhost
  connection: local
  gather_facts: true
  name: "Convert human inputs to bytes for proper volume sizes."
#  This "function" assumes all inputs are in BYTES, if Bits is wanted replace B with b and add "isbits=true" to human_to_bytes
#
#
#

  tasks:
    - name: "Create local vars"
      ansible.builtin.set_fact:
        sizes:
          - "3gBasdfggg" 
          - "3tb"
          - "1 GB"
          - "1.5 GB"
          - "1 TB"
          - "2.5TB"
          - "3 T"
          - "125G"
          - "125GB"
          - "125"
          - "21 gb"
          - "1,2 g"
        reserve: 10

    - name: Debug                                                                                                       #https://docs.saltproject.io/en/master/topics/jinja/index.html
      ansible.builtin.debug:
        msg:                        "Input: {{ item }}, value in bytes: {{ (item | replace('b','B') | human_to_bytes(default_unit='GB') / ( 1 - ( reserve / 100 )) | round(0,'ceil') ) | int }}"
      loop: "{{ sizes }}"
