---
- hosts: localhost
  connection: local
  gather_facts: true
  name: Vars demo1

  tasks:
  - name: "Create local vars/dicts"
    set_fact:
      animals1:
        dog:
          legs:     4
          color:    brown
      animals2: 
        fish:
          legs:     0
          color:    orange
        zebra:
          legs:     4
          color:    "white/black"
        duck:
          legs:     2
          color:    white
    tags: always


  - name: "loop over inital dict"
    debug:
      msg: "A {{ item.key }} has {{ item.value.legs }} legs and is {{ item.value.color }}"
    loop: "{{ animals1 | dict2items }}"
    tags: always

  - name: "Adding cats to the aminmal1 list" 
    set_fact:
      animals1: "{{ animals1 | combine({ 'cat': { 'legs': '4', 'color': 'grey' } }) }}"         
    tags: always

  - name: "Adding ducks to the animal1 list"
    set_fact:
      animals1: "{{ animals1 | combine({ 'duck': { 'legs': '2', 'color': 'white' } }) }}"
    tags: always

  - name: "Adding an elephant"
    set_fact:
      animals1: "{{ animals1 | combine({ 'elephant': { 'legs': '4', 'color': 'grey' } }) }}"
    tags: always

  - name: "Loop over the new dict"
    debug:
      msg: "A {{ item.key }} has {{ item.value.legs }} legs and is {{ item.value.color }}"
    loop: "{{ animals1 | dict2items }}"
    tags: always

  - name: "join two dicts without limitation"
    set_fact:
      animals3: "{{animals1 | combine(animals2)}}"
    tags: always

  - name: "debug animals3"
    debug:
      var: animals3
    tags: always

  - name: "Create a new list and make sure the key in animals1"
    set_fact:
      animals4: "{{ (animals4 | default({})) |  combine ( {item.key : item.value})  }}"
    loop: "{{ (animals1 | combine(animals2) ) | dict2items }}"
    when:
      - item.key is in animals1
    tags: always

  - name: "debug the animals4 var"
    debug:
      var: animals4
    tags: always




